#!/usr/bin/env python3
"""Post-hoc: sample real conflict pairs (synthetic locked scenarios +
MemoryAgentBench extension) into annotation/audit_sample.csv for independent
validation (see ANALYSIS_PLAN_ADDENDUM.md item A4). Writes only the fields
generated by construction; the human_* columns are left EMPTY -- this script
does not and cannot perform human validation itself.
"""
from __future__ import annotations

import csv
import random
from pathlib import Path

from branchmem.benchmark.scenario_generator import ScenarioConfig, ScenarioGenerator

SEED = 2026
N_SCENARIOS = 60
DIVERGENCE_SPANS = [4.0, 10.0, 20.0]
N_SAMPLE = 40
OUT_PATH = Path(__file__).resolve().parents[1] / "annotation" / "audit_sample.csv"

FIELDS = [
    "example_id", "source_dataset", "ancestor_value", "branch_a_value", "branch_a_source",
    "branch_a_confidence", "branch_b_value", "branch_b_source", "branch_b_confidence",
    "generated_conflict_type", "generated_correct_value", "human_is_extraction_correct",
    "human_is_conflict_type_correct", "human_preferred_resolution", "human_should_flag",
    "human_notes",
]


def main() -> None:
    generator = ScenarioGenerator()
    n_per_span = N_SCENARIOS // len(DIVERGENCE_SPANS)
    scenarios = []
    for i, span in enumerate(DIVERGENCE_SPANS):
        config = ScenarioConfig(divergence_span=span)
        scenarios.extend(generator.generate(n_per_span, config, seed=SEED + i))

    rows = []
    for sc in scenarios:
        fact_lookup = {f.fact_id: f for f in sc.branch_a.facts + sc.branch_b.facts}
        ancestor_lookup = {f.key(): f.value for f in sc.ancestor.facts}
        for pair in sc.conflict_pairs:
            fact_a, fact_b = fact_lookup[pair.fact_a_id], fact_lookup[pair.fact_b_id]
            rows.append({
                "example_id": f"{sc.scenario_id}:{fact_a.entity}|{fact_a.predicate}",
                "source_dataset": "synthetic_locked_n60",
                "ancestor_value": ancestor_lookup.get(fact_a.key(), ""),
                "branch_a_value": fact_a.value, "branch_a_source": fact_a.source,
                "branch_a_confidence": fact_a.confidence,
                "branch_b_value": fact_b.value, "branch_b_source": fact_b.source,
                "branch_b_confidence": fact_b.confidence,
                "generated_conflict_type": pair.conflict_type or "orthogonal",
                "generated_correct_value": pair.ground_truth_value or "",
                "human_is_extraction_correct": "", "human_is_conflict_type_correct": "",
                "human_preferred_resolution": "", "human_should_flag": "", "human_notes": "",
            })

    rng = random.Random(SEED)
    sample = rng.sample(rows, k=min(N_SAMPLE, len(rows)))
    sample.sort(key=lambda r: r["example_id"])

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS)
        writer.writeheader()
        writer.writerows(sample)
    print(f"Wrote {len(sample)} rows to {OUT_PATH}")


if __name__ == "__main__":
    main()
